# Generated by Django 5.1.3 on 2025-02-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نوع غذا')),
                ('price', models.FloatField(verbose_name='قیمت غذا')),
            ],
            options={
                'verbose_name': 'نوع غذا',
                'verbose_name_plural': 'انواع غذا',
                'db_table': 'foods_type',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='نام غذا')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='food_app.foodtype', verbose_name='نوع غذا')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
                'db_table': 'foods',
            },
        ),
    ]
