# Generated by Django 5.1.3 on 2025-02-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
        ('reservation_app', '0003_alter_dailymealplanmodel_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodPromise',
            new_name='FoodPromiseModel',
        ),
        migrations.RenameField(
            model_name='foodmodel',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='foodmodel',
            old_name='food_type',
            new_name='type',
        ),
    ]
