# Generated by Django 5.1.3 on 2025-02-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام مخلفات')),
            ],
            options={
                'verbose_name': 'مخلفات',
                'verbose_name_plural': 'مخلفات',
                'db_table': 'side_dishes',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='side_dishes',
            field=models.ManyToManyField(to='food_app.sidedishes', verbose_name='مخلفات'),
        ),
    ]
