# Generated by Django 5.1.3 on 2025-02-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_sidedishes_food_side_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='side_dishes',
            field=models.ManyToManyField(null=True, to='food_app.sidedishes', verbose_name='مخلفات'),
        ),
    ]
