# Generated by Django 5.1.3 on 2025-02-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_food_side_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نوشیدنی')),
            ],
            options={
                'verbose_name': 'نوشیدنی',
                'verbose_name_plural': 'نوشیدنی ها',
                'db_table': 'drinks',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink', to='food_app.drink', verbose_name='نوشیدنی'),
        ),
    ]
