# Generated by Django 5.1.3 on 2025-02-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_food_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink', to='food_app.drink', verbose_name='نوشیدنی'),
        ),
    ]
