# Generated by Django 5.1.3 on 2025-02-08 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_alter_food_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='side_dishes',
            field=models.ManyToManyField(blank=True, null=True, to='food_app.sidedishes', verbose_name='مخلفات'),
        ),
    ]
