# Generated by Django 5.1.3 on 2025-02-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMealPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1403, verbose_name='سال')),
                ('number_of_week', models.IntegerField(default=48, verbose_name='شماره هفته در سال')),
            ],
            options={
                'verbose_name': ('برنامه هفتگی',),
                'verbose_name_plural': 'برنامه های هفتگی',
                'db_table': 'week_meal_plan',
            },
        ),
        migrations.CreateModel(
            name='DailyMealPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'Saturday'), ('یکشنبه', 'Sunday'), ('دوشنبه', 'Monday'), ('سه شنبه', 'Tuesday '), ('چهارشنبه', 'Wednesday '), ('پنجشنبه', 'Thursday  '), ('جمعه', 'Friday')], max_length=50, verbose_name='روز هفته')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_model', to='food_app.foodmodel', verbose_name='غذا')),
                ('food_promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_promise', to='food_app.foodpromise', verbose_name='زمان وعده غذایی')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='reservation_app.weekmealplanmodel', verbose_name='برنامه هفته')),
            ],
            options={
                'verbose_name': 'وعده غذایی',
                'verbose_name_plural': 'وعده های غذایی',
                'db_table': 'dayli_meal_plan',
            },
        ),
    ]
