# Generated by Django 5.1.3 on 2025-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealplanmodel',
            name='day',
            field=models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یکشنبه'), ('Monday', 'دوشنبه'), ('Tuesday', 'سه شنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنجشنبه'), ('Friday', 'جمعه')], max_length=50, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='weekmealplanmodel',
            name='number_of_week',
            field=models.IntegerField(default=48, unique=True, verbose_name='شماره هفته در سال'),
        ),
    ]
