# Generated by Django 5.1.3 on 2025-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_alter_dailymealplanmodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealplanmodel',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=50, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='weekmealplanmodel',
            name='number_of_week',
            field=models.IntegerField(default=48, verbose_name='شماره هفته در سال'),
        ),
    ]
